// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLNetDemoML.Model
{
    public class ModelInput
    {
        [ColumnName("YearsOfExperience"), LoadColumn(0)]
        public float YearsOfExperience { get; set; }


        [ColumnName("Salary"), LoadColumn(1)]
        public float Salary { get; set; }


    }
}
